# Copyright 2023 DeepMind Technologies Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

""" Class for evaluating programs proposed by the Sampler."""
from __future__ import annotations

from abc import abstractmethod, ABC
import ast
import time
from collections.abc import Sequence
import copy
from typing import Any, Type
import profile
import multiprocessing

import numpy as np

from llmode import code_manipulation
from llmode import buffer
from llmode import evaluator_accelerate


class _FunctionLineVisitor(ast.NodeVisitor):
    """ Visitor that finds the last line number of a function with a given name."""

    def __init__(self, target_function_name: str) -> None:
        self._target_function_name: str = target_function_name
        self._function_end_line: int | None = None

    def visit_FunctionDef(self, node: Any) -> None: 
        """ Collect the end line number of the target function."""
        if node.name == self._target_function_name:
            self._function_end_line = node.end_lineno
        self.generic_visit(node)

    @property
    def function_end_line(self) -> int:
        """ Line number of the final line of function `target_function_name`."""
        assert self._function_end_line is not None 
        return self._function_end_line


def _trim_function_body(generated_code: str) -> str:
    """ Extract the body of the generated function, trimming anything after it.
    Please note that the indentation is REQUIRED !!!
    """
    if not generated_code:
        return ''

    code = f'def fake_function_header():\n{generated_code}'

    tree = None
    while tree is None:
        try:
            tree = ast.parse(code)
        
        except SyntaxError as e:
            if e.lineno is None: # Nothing could be saved when syntaxError
                return ''
            code = '\n'.join(code.splitlines()[:e.lineno - 1])

    if not code:
        return ''

    visitor = _FunctionLineVisitor('fake_function_header')
    visitor.visit(tree)
    body_lines = code.splitlines()[1:visitor.function_end_line]
    return '\n'.join(body_lines) + '\n\n'


def _sample_to_program(
        generated_code: str,
        version_generated: int | None,
        template: code_manipulation.Program,
        function_to_evolve: str,
) -> tuple[code_manipulation.Function, str]:
    """ 
    Return the compiled generated function and the full runnable program.
    This function removes the content after the generated function body.
    """

    def _strip_leading_docstring(body: str, keep_docstring: bool) -> str:
        """Remove a top-level docstring literal from `body` when requested.

        When the template's evolve function already has a docstring, we prefer
        to keep that canonical docstring and drop any new leading docstring
        generated by the LLM inside the body. This avoids duplicated docstrings
        like:

            \"\"\"spec docstring\"\"\"
            \"\"\"Improved version ...\"\"\"
        """
        if not keep_docstring or not body:
            return body

        lines = body.splitlines()
        i = 0
        # Skip initial empty/whitespace-only lines
        while i < len(lines) and not lines[i].strip():
            i += 1
        if i >= len(lines):
            return body

        stripped = lines[i].lstrip()
        if stripped.startswith('"""'):
            quote = '"""'
        elif stripped.startswith("'''"):
            quote = "'''"
        else:
            return body

        # If the closing quotes appear on the same line, drop just this line.
        if stripped.count(quote) >= 2:
            i += 1
        else:
            # Skip lines until we find the closing quote.
            i += 1
            while i < len(lines) and quote not in lines[i]:
                i += 1
            if i < len(lines):
                i += 1

        # Skip any trailing blank lines after the docstring.
        while i < len(lines) and not lines[i].strip():
            i += 1

        if i >= len(lines):
            return ''
        return '\n'.join(lines[i:]) + '\n\n'

    body = _trim_function_body(generated_code)

    # Check whether the template's evolve function already has a canonical
    # docstring; if so, strip any leading docstring literal from the generated
    # body before injecting it, so only the spec docstring remains.
    try:
        template_func = template.get_function(function_to_evolve)
        has_template_doc = bool((template_func.docstring or '').strip())
    except ValueError:
        has_template_doc = False

    if has_template_doc:
        body = _strip_leading_docstring(body, keep_docstring=True)

    if version_generated is not None:
        body = code_manipulation.rename_function_calls(
            code=body,
            source_name=f'{function_to_evolve}_v{version_generated}',
            target_name=function_to_evolve
        )

    program = copy.deepcopy(template)
    evolved_function = program.get_function(function_to_evolve)
    evolved_function.body = body
    
    return evolved_function, str(program)


class Sandbox(ABC):
    """ Sandbox for executing generated code. """

    @abstractmethod
    def run(
            self,
            program: str,
            function_to_run: str,
            function_to_evolve: str,
            inputs: Any,  
            test_input: str, 
            timeout_seconds: int,
            **kwargs
    ) -> tuple[Any, bool]:
        """ Return `function_to_run(test_input)` and whether execution succeeded. """
        raise NotImplementedError(
            'Must provide a sandbox for executing untrusted code.')


class LocalSandbox(Sandbox):
    """
    Secure environment for executing and evaluating LLM generated programs.
    Prevents harmful operations, limits resource usage, and enforces timeouts.
    Returns a 'score' for the executed program.
    """

    def __init__(self, verbose=False, numba_accelerate=False):
        """
        Initialize Sandbox.
        
        Args:
        verbose (bool): Enable detailed output.
        numba_accelerate (bool): Use Numba for acceleration of evaluation (limited compatibility). 
        """
        self._verbose = verbose
        self._numba_accelerate = numba_accelerate


    def run(self, program: str, function_to_run: str, function_to_evolve: str, 
        inputs: Any, test_input: str, timeout_seconds: int, **kwargs) -> tuple[Any, bool]:
        """
        Execute the given program sample and return its score and success status.
        
        Note: This sandbox is specific to the equation program skeleton discovery problem.
        """

        dataset = inputs[test_input]
        result_queue = multiprocessing.Queue()
        
        process = multiprocessing.Process(
            target=self._compile_and_run_function,
            args=(program, function_to_run, function_to_evolve, dataset, self._numba_accelerate, result_queue)
        )
        process.start()
        process.join(timeout=timeout_seconds)

        # if the process is not finished in time, terminate
        if process.is_alive():
            process.terminate()
            process.join()
            results = None, False
        else:
            results = self._get_results(result_queue)
        
        if self._verbose:
            self._print_evaluation_details(program, results, **kwargs)

        return results


    def _get_results(self, queue):
        for _ in range(5):
            if not queue.empty():
                return queue.get_nowait()
            time.sleep(0.1)
        return None, False


    def _print_evaluation_details(self, program, results, **kwargs):
        print('================= Evaluated Program =================')
        function = code_manipulation.text_to_program(program).get_function(kwargs.get('func_to_evolve', 'system'))
        print(f'{str(function).strip()}\n-----------------------------------------------------')
        print(f'Score: {results}\n=====================================================\n\n')



    def _compile_and_run_function(self, program, function_to_run, function_to_evolve, 
                                  dataset, numba_accelerate, result_queue):
        try:
            # optimize the code (decorate function_to_run with @numba.jit())
            if numba_accelerate:
                program = evaluator_accelerate.add_numba_decorator(
                    program=program,
                    function_to_evolve=function_to_evolve
                )
            
            # execute the program, map func/var/class to global namespace
            all_globals_namespace = {}
            exec(program, all_globals_namespace)
            function_to_run = all_globals_namespace[function_to_run]
            results = function_to_run(dataset)
            
            if not isinstance(results, (int, float)):
                result_queue.put((None, False))
                return
            result_queue.put((results, True))
            
        # if raise any exception, execution is failed
        except Exception as e:
            print(f"Execution Error: {e}")
            result_queue.put((None, False))



def _calls_ancestor(program: str, function_to_evolve: str) -> bool:
    """ Return whether the generated function is calling an earlier version. """
    for name in code_manipulation.get_functions_called(program):
        if name.startswith(f'{function_to_evolve}_v'):
            return True
    return False



class Evaluator:
    """ Class that analyses functions generated by LLMs. """

    def __init__(
            self,
            database: buffer.ExperienceBuffer,
            template: code_manipulation.Program,
            function_to_evolve: str,
            function_to_run: str | None,
            inputs: Sequence[Any],
            timeout_seconds: int = 30,
            sandbox_class: Type[Sandbox] = Sandbox,
            problem_name: str | None = None,
    ):
        self._database = database
        self._template = template
        self._function_to_evolve = function_to_evolve
        self._function_to_run = function_to_run
        self._inputs = inputs
        self._timeout_seconds = timeout_seconds
        self._sandbox = sandbox_class()
        self._problem_name = problem_name

    def analyse(
            self,
            sample: str,
            island_id: int | None,
            version_generated: int | None,
            **kwargs 
    ) -> None:
        """ Compile the hypothesis sample into a program and executes it on test inputs. """
        new_function, program = _sample_to_program(
            sample, version_generated, self._template, self._function_to_evolve)

        # Attach basic metadata from kwargs as early as possible so that
        # downstream components (e.g., ExperienceBuffer / Cluster) can see
        # correct sample orders even before registration.
        global_sample_nums = kwargs.get('global_sample_nums', None)
        sample_time = kwargs.get('sample_time', None)
        if global_sample_nums is not None:
            new_function.global_sample_nums = global_sample_nums
        if sample_time is not None:
            new_function.sample_time = sample_time

        # Optionally inject LLM-inferred (or explicitly provided) parameter
        # distributions into the program so that legacy specification-based
        # `evaluate` functions can access them as a global `param_distributions`
        # dictionary.
        param_distributions = kwargs.pop('param_distributions', None)
        if param_distributions is not None:
            kwargs['param_distributions'] = param_distributions

        if param_distributions is not None and self._function_to_run is not None:
            import json as _json
            header = f"param_distributions = {_json.dumps(param_distributions)}\n\n"
            program = header + program

        scores_per_test = {}
        new_function.param_distributions = param_distributions

        time_reset = time.time()

        # Two evaluation modes:
        #   1) Legacy spec-based: use @evaluate.run inside the spec via Sandbox.
        #   2) Centralized evaluation: use synthetic likelihood against observed data.
        if self._function_to_run is not None:
            # Legacy path: run the spec's evaluate function inside the sandbox.
            for current_input in self._inputs:
                test_output, runs_ok = self._sandbox.run(
                    program,
                    self._function_to_run,
                    self._function_to_evolve,
                    self._inputs,
                    current_input,
                    self._timeout_seconds,
                )

                if runs_ok and not _calls_ancestor(program, self._function_to_evolve) and test_output is not None:
                    if not isinstance(test_output, (int, float)):
                        print(f'Error: test_output is {test_output}')
                        raise ValueError('@function.run did not return an int/float score.')
                    # Round legacy evaluation scores to 3 decimal places.
                    # scores_per_test[current_input] = round(float(test_output), 3)
                    scores_per_test[current_input] = int(round(float(test_output)))

                    
        else:
            # Centralized evaluation path: use log synthetic likelihood.
            from llmode import synthetic_likelihood

            problem_name = kwargs.get('problem_name') or self._problem_name
            if problem_name is None:
                raise ValueError(
                    'Centralized evaluation requires `problem_name` to be provided.'
                )

            # Obtain an executable callable for the evolved system by executing
            # the full program and reading the function from its globals.
            all_globals_namespace: dict[str, Any] = {}
            exec(program, all_globals_namespace)
            system_func = all_globals_namespace[self._function_to_evolve]

            sample_order = getattr(new_function, 'global_sample_nums', None)

            log_sl_score = synthetic_likelihood.evaluate_system_logsl(
                system_func=system_func,
                problem_name=problem_name,
                param_distributions=param_distributions,
                sample_order=sample_order,
            )
            if log_sl_score is not None and np.isfinite(log_sl_score):
                # Centralized evaluation produces a single scalar score
                # (log synthetic likelihood) for the whole system; round to 3 decimals.
                # scores_per_test['log_sl'] = round(float(log_sl_score), 3)
                scores_per_test['log_sl'] = int(round(float(log_sl_score)))

        evaluate_time = time.time() - time_reset

        if scores_per_test:
            # print('Scores per test:')
            # print(island_id)
            # print(scores_per_test)
            # print(64*'-')
            self._database.register_program(
                new_function,
                island_id,
                scores_per_test,
                **kwargs,
                evaluate_time=evaluate_time,
            )
        
        else:
            profiler: profile.Profiler = kwargs.get('profiler', None)
            if profiler:
                global_sample_nums = kwargs.get('global_sample_nums', None)
                sample_time = kwargs.get('sample_time', None)
                llm_source = kwargs.get('llm_source', None)
                llm_model_name = kwargs.get('llm_model_name', None)
                new_function.global_sample_nums = global_sample_nums
                new_function.score = None
                new_function.sample_time = sample_time
                new_function.evaluate_time = evaluate_time
                if llm_source is not None:
                    new_function.llm_source = llm_source
                if llm_model_name is not None:
                    new_function.llm_model_name = llm_model_name
                profiler.register_function(new_function)
