# Copyright 2023 DeepMind Technologies Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

""" Class for evaluating programs proposed by the Sampler."""
from __future__ import annotations

from abc import abstractmethod, ABC
import os
import ast
import time
from collections.abc import Sequence
import copy
from typing import Any, Type
import profile
import multiprocessing

import numpy as np

from llmode import code_manipulation
from llmode import buffer
from llmode import evaluator_accelerate


# Global flag to control debug printing (prompts, intermediate evaluations, etc.).
DEBUG_PRINTS = os.environ.get("LLMODE_DEBUG_PRINTS", "0") == "1"

class _FunctionLineVisitor(ast.NodeVisitor):
    """ Visitor that finds the last line number of a function with a given name."""

    def __init__(self, target_function_name: str) -> None:
        self._target_function_name: str = target_function_name
        self._function_end_line: int | None = None

    def visit_FunctionDef(self, node: Any) -> None: 
        """ Collect the end line number of the target function."""
        if node.name == self._target_function_name:
            self._function_end_line = node.end_lineno
        self.generic_visit(node)

    @property
    def function_end_line(self) -> int:
        """ Line number of the final line of function `target_function_name`."""
        assert self._function_end_line is not None 
        return self._function_end_line


def _trim_function_body(generated_code: str) -> str:
    """ Extract the body of the generated function, trimming anything after it.
    Please note that the indentation is REQUIRED !!!
    """
    if not generated_code:
        return ''

    code = f'def fake_function_header():\n{generated_code}'

    tree = None
    while tree is None:
        try:
            tree = ast.parse(code)
        
        except SyntaxError as e:
            if e.lineno is None: # Nothing could be saved when syntaxError
                return ''
            code = '\n'.join(code.splitlines()[:e.lineno - 1])

    if not code:
        return ''

    visitor = _FunctionLineVisitor('fake_function_header')
    visitor.visit(tree)
    body_lines = code.splitlines()[1:visitor.function_end_line]
    return '\n'.join(body_lines) + '\n\n'


def _sample_to_program(
        generated_code: str,
        version_generated: int | None,
        template: code_manipulation.Program,
        function_to_evolve: str,
) -> tuple[code_manipulation.Function, str]:
    """ 
    Return the compiled generated function and the full runnable program.
    This function removes the content after the generated function body.
    """

    def _strip_leading_docstring(body: str, keep_docstring: bool) -> str:
        """Remove a top-level docstring literal from `body` when requested.

        When the template's evolve function already has a docstring, we prefer
        to keep that canonical docstring and drop any new leading docstring
        generated by the LLM inside the body. This avoids duplicated docstrings
        like:

            \"\"\"spec docstring\"\"\"
            \"\"\"Improved version ...\"\"\"
        """
        if not keep_docstring or not body:
            return body

        lines = body.splitlines()
        i = 0
        # Skip initial empty/whitespace-only lines
        while i < len(lines) and not lines[i].strip():
            i += 1
        if i >= len(lines):
            return body

        stripped = lines[i].lstrip()
        if stripped.startswith('"""'):
            quote = '"""'
        elif stripped.startswith("'''"):
            quote = "'''"
        else:
            return body

        # If the closing quotes appear on the same line, drop just this line.
        if stripped.count(quote) >= 2:
            i += 1
        else:
            # Skip lines until we find the closing quote.
            i += 1
            while i < len(lines) and quote not in lines[i]:
                i += 1
            if i < len(lines):
                i += 1

        # Skip any trailing blank lines after the docstring.
        while i < len(lines) and not lines[i].strip():
            i += 1

        if i >= len(lines):
            return ''
        return '\n'.join(lines[i:]) + '\n\n'

    body = _trim_function_body(generated_code)

    # Check whether the template's evolve function already has a canonical
    # docstring; if so, strip any leading docstring literal from the generated
    # body before injecting it, so only the spec docstring remains.
    try:
        template_func = template.get_function(function_to_evolve)
        has_template_doc = bool((template_func.docstring or '').strip())
    except ValueError:
        has_template_doc = False

    if has_template_doc:
        body = _strip_leading_docstring(body, keep_docstring=True)

    if version_generated is not None:
        body = code_manipulation.rename_function_calls(
            code=body,
            source_name=f'{function_to_evolve}_v{version_generated}',
            target_name=function_to_evolve
        )

    program = copy.deepcopy(template)
    evolved_function = program.get_function(function_to_evolve)
    evolved_function.body = body
    
    return evolved_function, str(program)


class Sandbox(ABC):
    """ Sandbox for executing generated code. """

    @abstractmethod
    def run(
            self,
            program: str,
            function_to_run: str,
            function_to_evolve: str,
            inputs: Any,  
            test_input: str, 
            timeout_seconds: int,
            **kwargs
    ) -> tuple[Any, bool]:
        """ Return `function_to_run(test_input)` and whether execution succeeded. """
        raise NotImplementedError(
            'Must provide a sandbox for executing untrusted code.')


class LocalSandbox(Sandbox):
    """
    Secure environment for executing and evaluating LLM generated programs.
    Prevents harmful operations, limits resource usage, and enforces timeouts.
    Returns a 'score' for the executed program.
    """

    def __init__(self, verbose=False, numba_accelerate=False):
        """
        Initialize Sandbox.
        
        Args:
        verbose (bool): Enable detailed output.
        numba_accelerate (bool): Use Numba for acceleration of evaluation (limited compatibility). 
        """
        self._verbose = verbose
        self._numba_accelerate = numba_accelerate


    def run(self, program: str, function_to_run: str, function_to_evolve: str, 
        inputs: Any, test_input: str, timeout_seconds: int, **kwargs) -> tuple[Any, bool]:
        """
        Execute the given program sample and return its score and success status.
        
        Note: This sandbox is specific to the equation program skeleton discovery problem.
        """

        dataset = inputs[test_input]
        result_queue = multiprocessing.Queue()
        
        process = multiprocessing.Process(
            target=self._compile_and_run_function,
            args=(program, function_to_run, function_to_evolve, dataset, self._numba_accelerate, result_queue)
        )
        process.start()
        process.join(timeout=timeout_seconds)

        # if the process is not finished in time, terminate
        if process.is_alive():
            process.terminate()
            process.join()
            results = None, False
        else:
            results = self._get_results(result_queue)
        
        if self._verbose:
            self._print_evaluation_details(program, results, **kwargs)

        return results


    def _get_results(self, queue):
        for _ in range(5):
            if not queue.empty():
                return queue.get_nowait()
            time.sleep(0.1)
        return None, False


    def _print_evaluation_details(self, program, results, **kwargs):
        print('================= Evaluated Program =================')
        function = code_manipulation.text_to_program(program).get_function(kwargs.get('func_to_evolve', 'system'))
        print(f'{str(function).strip()}\n-----------------------------------------------------')
        print(f'Score: {results}\n=====================================================\n\n')



    def _compile_and_run_function(self, program, function_to_run, function_to_evolve, 
                                  dataset, numba_accelerate, result_queue):
        try:
            # optimize the code (decorate function_to_run with @numba.jit())
            if numba_accelerate:
                program = evaluator_accelerate.add_numba_decorator(
                    program=program,
                    function_to_evolve=function_to_evolve
                )
            
            # execute the program, map func/var/class to global namespace
            all_globals_namespace = {}
            exec(program, all_globals_namespace)
            function_to_run = all_globals_namespace[function_to_run]
            results = function_to_run(dataset)
            
            if not isinstance(results, (int, float)):
                result_queue.put((None, False))
                return
            result_queue.put((results, True))
            
        # if raise any exception, execution is failed
        except Exception as e:
            print(f"Execution Error: {e}")
            result_queue.put((None, False))



def _calls_ancestor(program: str, function_to_evolve: str) -> bool:
    """ Return whether the generated function is calling an earlier version. """
    for name in code_manipulation.get_functions_called(program):
        if name.startswith(f'{function_to_evolve}_v'):
            return True
    return False


def _compute_implausibility_report(
    system_func: Any,
    param_distributions: dict[str, Any],
    problem_name: str,
) -> str | None:
    """Simulate a representative trajectory and return implausibility report text."""
    if param_distributions is None:
        return None

    from llmode import initial_condition_utils
    from llmode import ode_simulator
    from llmode import param_utils

    try:
        means, _ = param_utils.param_distributions_to_arrays(param_distributions)
    except Exception:
        return None

    try:
        ic_config = initial_condition_utils.load_ic_config(problem_name)
        trajectories, _t, _ic = ode_simulator.simulate_from_config(
            system_func=system_func,
            params=means,
            config=ic_config,
            sample_size=None,
            random_seed=ic_config.get("random_seed", None),
            verbose=False,
        )
        report = ode_simulator.get_unplausible_trajectory_report(
            trajectories=trajectories,
            config=ic_config,
            check_nans=True,
        )
        return report
    except Exception as e:
        print(f"[Implausibility report] Failed to compute report: {e}")
        return None


def _print_param_eval_summary(
    step_idx: int,
    max_steps: int,
    score: float | None,
    new_function: code_manipulation.Function,
    eval_time: float | None = None,
    llm_source: str | None = None,
    llm_model_name: str | None = None,
) -> None:
    """Pretty-print evaluation info for a given parameter set, mirroring Profiler style."""
    try:
        from llmode import param_utils as _param_utils_summary
        num_params = _param_utils_summary.count_params_used(new_function.body)
    except Exception:
        num_params = 0

    sample_orders = getattr(new_function, 'global_sample_nums', None)
    sample_orders = sample_orders if sample_orders is not None else 0
    sample_time = getattr(new_function, 'sample_time', None)

    if not DEBUG_PRINTS:
        return
    print(f"Step: {step_idx}/{max_steps}")
    print(f"Parameters used: {num_params}")
    print(f"Score        : {str(score)}")
    print(f"Sample time  : {str(sample_time)}")
    print(f"Evaluate time: {str(eval_time)}")
    print(f"Sample orders: {str(sample_orders)}")
    if llm_source is not None or llm_model_name is not None:
        print(f"LLM backend  : {llm_source or 'unknown'}")
        if llm_model_name is not None:
            print(f"LLM model    : {llm_model_name}")
    print(f"{'='*54}\n")



class Evaluator:
    """ Class that analyses functions generated by LLMs. """

    def __init__(
            self,
            database: buffer.ExperienceBuffer,
            template: code_manipulation.Program,
            function_to_evolve: str,
            function_to_run: str | None,
            inputs: Sequence[Any],
            timeout_seconds: int = 30,
            sandbox_class: Type[Sandbox] = Sandbox,
            problem_name: str | None = None,
    ):
        self._database = database
        self._template = template
        self._function_to_evolve = function_to_evolve
        self._function_to_run = function_to_run
        self._inputs = inputs
        self._timeout_seconds = timeout_seconds
        self._sandbox = sandbox_class()
        self._problem_name = problem_name

    def analyse(
            self,
            sample: str,
            island_id: int | None,
            version_generated: int | None,
            **kwargs 
    ) -> None:
        """ Compile the hypothesis sample into a program and executes it on test inputs. """
        new_function, program = _sample_to_program(
            sample, version_generated, self._template, self._function_to_evolve)

        # Attach basic metadata from kwargs as early as possible so that
        # downstream components (e.g., ExperienceBuffer / Cluster) can see
        # correct sample orders even before registration.
        global_sample_nums = kwargs.get('global_sample_nums', None)
        sample_time = kwargs.get('sample_time', None)
        if global_sample_nums is not None:
            new_function.global_sample_nums = global_sample_nums
        if sample_time is not None:
            new_function.sample_time = sample_time

        # Optionally inject LLM-inferred (or explicitly provided) parameter
        # distributions into the program so that legacy specification-based
        # `evaluate` functions can access them as a global `param_distributions`
        # dictionary.
        param_distributions = kwargs.pop('param_distributions', None)
        if param_distributions is not None:
            kwargs['param_distributions'] = param_distributions

        if param_distributions is not None and self._function_to_run is not None:
            import json as _json
            header = f"param_distributions = {_json.dumps(param_distributions)}\n\n"
            program = header + program

        # Control whether to run parameter-optimization loop for this program.
        enable_param_optim = kwargs.pop('enable_param_optim', True)

        scores_per_test = {}
        new_function.param_distributions = param_distributions

        time_reset = time.time()

        # Two evaluation modes:
        #   1) Legacy spec-based: use @evaluate.run inside the spec via Sandbox.
        #   2) Centralized evaluation: use synthetic likelihood against observed data.
        if self._function_to_run is not None:
            # Legacy path: run the spec's evaluate function inside the sandbox.
            for current_input in self._inputs:
                test_output, runs_ok = self._sandbox.run(
                    program,
                    self._function_to_run,
                    self._function_to_evolve,
                    self._inputs,
                    current_input,
                    self._timeout_seconds,
                )

                if runs_ok and not _calls_ancestor(program, self._function_to_evolve) and test_output is not None:
                    if not isinstance(test_output, (int, float)):
                        print(f'Error: test_output is {test_output}')
                        raise ValueError('@function.run did not return an int/float score.')
                    # Round legacy evaluation scores to 2 decimal places.
                    scores_per_test[current_input] = round(float(test_output), 2)

                    
        else:
            # Centralized evaluation path: use synthetic likelihood against
            # observed summary statistics and optionally iterate to optimize
            # parameter priors for this specific ODE structure.
            from llmode import synthetic_likelihood
            from llmode import param_utils

            problem_name = kwargs.get('problem_name') or self._problem_name
            if problem_name is None:
                raise ValueError(
                    'Centralized evaluation requires `problem_name` to be provided.'
                )

            # Obtain an executable callable for the evolved system by executing
            # the full program and reading the function from its globals.
            all_globals_namespace: dict[str, Any] = {}
            exec(program, all_globals_namespace)
            system_func = all_globals_namespace[self._function_to_evolve]

            # Prepare system code string for prompts.
            try:
                program_obj = code_manipulation.text_to_program(program)
                system_fn_obj = program_obj.get_function(self._function_to_evolve)
                system_code_str = str(system_fn_obj)
            except Exception:
                system_code_str = ""

            sample_order = getattr(new_function, 'global_sample_nums', None)

            config_obj = kwargs.get('config', None)
            max_steps = 1
            patience = 0
            rel_thresh = 0.1
            if enable_param_optim and config_obj is not None:
                try:
                    max_steps = int(getattr(config_obj, 'param_optim_steps', 1))
                    patience = int(getattr(config_obj, 'param_optim_patience', 3))
                    rel_thresh = float(
                        getattr(config_obj, 'param_optim_rel_improvement', 0.1)
                    )
                except Exception:
                    max_steps = 1
                    patience = 3
                    rel_thresh = 0.1
            if max_steps < 1:
                max_steps = 1
            if patience < 1:
                patience = 1
            if rel_thresh <= 0.0:
                rel_thresh = 0.1

            # If no parameter priors are available yet (e.g., centralized AKI
            # problems), run an initial parameter-inference call using the
            # base spec_parameters_{problem}.txt template.
            if param_distributions is None and config_obj is not None:
                try:
                    from llmode import param_utils as _param_utils_init

                    spec_path = os.path.join(
                        "specs_parameters", f"spec_parameters_{problem_name}.txt"
                    )
                    init_prompt = _param_utils_init.build_param_inference_prompt(
                        system_code=system_code_str or str(system_func),
                        spec_template_path=spec_path,
                        function_name=self._function_to_evolve,
                    )
                    if DEBUG_PRINTS:
                        print("[Generated Prompt for Initial Parameter Inference]")
                        print(init_prompt)
                    init_params = _param_utils_init.run_param_optimization_llm(
                        init_prompt,
                        config_obj,
                    )
                except Exception as e:
                    print(f"[Initial param inference] Failed: {e}")
                    init_params = None

                if init_params is not None:
                    param_distributions = init_params
                    kwargs['param_distributions'] = init_params
                    new_function.param_distributions = init_params

            if param_distributions is None or not enable_param_optim or max_steps == 1:
                # Legacy behavior: evaluate once and use that score.
                score, _feedback = synthetic_likelihood.evaluate_system_logsl_with_feedback(
                    system_func=system_func,
                    problem_name=problem_name,
                    param_distributions=param_distributions,
                    verbose=False,
                    sample_order=sample_order,
                )
                print(
                    f"[Centralized evaluation] Sample {sample_order}: "
                    f"logSL={score if score is not None else 'None'} (no optimization)."
                )
                # After evaluating log synthetic likelihood, compute a quadratic
                # summary-statistics score for comparing ODE structures using the
                # final parameter distributions.
                if (
                    score is not None
                    and np.isfinite(score)
                    and param_distributions is not None
                ):
                    try:
                        from llmode import quadratic_score as _quadratic_score

                        quad = _quadratic_score.evaluate_system_quadratic_score(
                            system_func=system_func,
                            problem_name=problem_name,
                            param_distributions=param_distributions,
                            verbose=False,
                            sample_order=sample_order,
                        )
                    except Exception as e:
                        print(
                            f"[Centralized evaluation] Failed to compute quadratic score: {e}"
                        )
                        quad = None

                    if quad is not None and np.isfinite(quad):
                        scores_per_test['quadratic_score'] = round(float(quad), 2)
            else:
                # Full optimization loop over parameter priors for this structure,
                # with early stopping based on relative logSL improvement and
                # consecutive null-score attempts.
                best_params: dict[str, Any] = param_distributions
                best_score: float | None = None
                best_feedback: str | None = None
                best_implaus: str | None = None
                no_improve_count = 0
                null_score_count = 0

                # Initial evaluation with the LLM-inferred priors.
                t0 = time.time()
                score, feedback = synthetic_likelihood.evaluate_system_logsl_with_feedback(
                    system_func=system_func,
                    problem_name=problem_name,
                    param_distributions=best_params,
                    verbose=False,
                    sample_order=sample_order,
                )
                init_eval_time = time.time() - t0
                if score is None or not np.isfinite(score):
                    best_score = None
                    best_feedback = None
                    best_implaus = _compute_implausibility_report(
                        system_func=system_func,
                        param_distributions=best_params,
                        problem_name=problem_name,
                    )
                    if DEBUG_PRINTS:
                        print(
                            f"[Param optimization] Sample {sample_order}: "
                            "initial logSL=None (implausible trajectories)."
                        )
                else:
                    best_score = float(score)
                    best_feedback = feedback
                    best_implaus = None
                    no_improve_count = 0
                    null_score_count = 0
                    if DEBUG_PRINTS:
                        print(
                            f"[Param optimization] Sample {sample_order}: "
                            f"initial logSL={best_score:.3f}"
                        )
                _print_param_eval_summary(
                    step_idx=1,
                    max_steps=max_steps,
                    score=best_score,
                    new_function=new_function,
                    eval_time=init_eval_time,
                    llm_source=kwargs.get('llm_source', None),
                    llm_model_name=kwargs.get('llm_model_name', None),
                )

                # Iterative optimization: refine parameter priors up to max_steps.
                steps_done = 1
                while steps_done < max_steps:
                    mode = 'implausible' if best_score is None else 'log_sl'
                    try:
                        opt_prompt = param_utils.build_param_optimization_prompt(
                            system_code=system_code_str,
                            problem_name=problem_name,
                            current_params=best_params,
                            mode=mode,
                            implaus_report=best_implaus if mode == 'implausible' else None,
                            sl_feedback=best_feedback if mode == 'log_sl' else None,
                        )
                    except Exception as e:
                        print(f"[Param optimization] Failed to build prompt: {e}")
                        break

                    if DEBUG_PRINTS:
                        print(
                            f"\n[Param optimization] Sample {sample_order}: "
                            f"step {steps_done+1}/{max_steps}, mode={mode}, "
                            f"current_best_logSL="
                            f"{best_score if best_score is not None else 'None'}"
                        )
                        print("[Generated Prompt for Parameter Optimization]")
                        print(opt_prompt)

                    new_params = param_utils.run_param_optimization_llm(
                        opt_prompt,
                        config_obj,
                    )
                    if new_params is None:
                        break

                    t_step = time.time()
                    new_score, new_feedback = synthetic_likelihood.evaluate_system_logsl_with_feedback(
                        system_func=system_func,
                        problem_name=problem_name,
                        param_distributions=new_params,
                        verbose=False,
                        sample_order=sample_order,
                    )
                    step_eval_time = time.time() - t_step

                    if new_score is None or not np.isfinite(new_score):
                        # No finite score; compute implausibility report for this candidate.
                        new_implaus = _compute_implausibility_report(
                            system_func=system_func,
                            param_distributions=new_params,
                            problem_name=problem_name,
                        )
                        null_score_count += 1
                        no_improve_count = 0
                        if best_score is None:
                            # When all candidates so far have null scores, keep
                            # the *latest* candidate info, as requested.
                            best_params = new_params
                            best_implaus = new_implaus
                            best_feedback = None
                        if DEBUG_PRINTS:
                            print(
                                f"[Param optimization] Sample {sample_order}: "
                                f"step {steps_done+1} produced logSL=None; "
                                f"null_score_count={null_score_count}/{patience}."
                            )
                        if null_score_count >= patience:
                            break
                    else:
                        new_score_val = float(new_score)
                        # Reset null-score streak.
                        null_score_count = 0

                        if best_score is None:
                            # Any finite score counts as an improvement when we
                            # previously had no valid score.
                            no_improve_count = 0
                        else:
                            improvement = new_score_val - best_score
                            if improvement <= 0.0:
                                # Worse or equal score: definitely no improvement.
                                no_improve_count += 1
                            else:
                                # Relative improvement measured against the scale of
                                # the current best score. Use absolute value so that
                                # negative logSL values do not flip the sign.
                                denom = max(abs(best_score) + 1.0, 1.0)
                                rel_improvement = improvement / denom
                                if rel_improvement < rel_thresh:
                                    no_improve_count += 1
                                else:
                                    no_improve_count = 0

                        if best_score is None or new_score_val > best_score:
                            best_score = new_score_val
                            best_params = new_params
                            best_feedback = new_feedback
                            best_implaus = None

                        if DEBUG_PRINTS:
                            best_str = f"{best_score:.3f}" if best_score is not None else "None"
                            print(
                                f"[Param optimization] Sample {sample_order}: "
                                f"step {steps_done+1} produced logSL={new_score_val:.3f}; "
                                f"best_logSL={best_str}, "
                                f"no_improve_count={no_improve_count}/{patience}."
                            )
                            _print_param_eval_summary(
                                step_idx=steps_done + 1,
                                max_steps=max_steps,
                                score=new_score_val,
                                new_function=new_function,
                                eval_time=step_eval_time,
                                llm_source=kwargs.get('llm_source', None),
                                llm_model_name=kwargs.get('llm_model_name', None),
                            )

                        if best_score is not None and no_improve_count >= patience:
                            break

                    steps_done += 1

                # After optimization, record only the best candidate.
                final_score = best_score
                final_params = best_params
                if final_score is not None and np.isfinite(final_score):
                    print(
                        f"[Param optimization] Sample {sample_order}: "
                        f"final best logSL={final_score:.3f}"
                    )
                else:
                    print(
                        f"[Param optimization] Sample {sample_order}: "
                        "no finite logSL found; using latest implausible candidate."
                    )

                # Make sure downstream components see the best param priors.
                param_distributions = final_params
                kwargs['param_distributions'] = final_params
                new_function.param_distributions = final_params

                # After finishing logSL-based parameter optimization, compute a
                # quadratic summary-statistics score using the final parameter
                # distributions so that ODE structures can be compared on a
                # common quadratic scale.
                if param_distributions is not None:
                    try:
                        from llmode import quadratic_score as _quadratic_score

                        quad = _quadratic_score.evaluate_system_quadratic_score(
                            system_func=system_func,
                            problem_name=problem_name,
                            param_distributions=param_distributions,
                            verbose=False,
                            sample_order=sample_order,
                        )
                    except Exception as e:
                        print(
                            f"[Param optimization] Failed to compute quadratic score: {e}"
                        )
                        quad = None

                    if quad is not None and np.isfinite(quad):
                        scores_per_test['quadratic_score'] = round(float(quad), 2)

        evaluate_time = time.time() - time_reset

        if scores_per_test:
            # print('Scores per test:')
            # print(island_id)
            # print(scores_per_test)
            # print(64*'-')
            self._database.register_program(
                new_function,
                island_id,
                scores_per_test,
                **kwargs,
                evaluate_time=evaluate_time,
            )
        
        else:
            profiler: profile.Profiler = kwargs.get('profiler', None)
            if profiler:
                global_sample_nums = kwargs.get('global_sample_nums', None)
                sample_time = kwargs.get('sample_time', None)
                llm_source = kwargs.get('llm_source', None)
                llm_model_name = kwargs.get('llm_model_name', None)
                new_function.global_sample_nums = global_sample_nums
                new_function.score = None
                new_function.sample_time = sample_time
                new_function.evaluate_time = evaluate_time
                if llm_source is not None:
                    new_function.llm_source = llm_source
                if llm_model_name is not None:
                    new_function.llm_model_name = llm_model_name
                profiler.register_function(new_function)
